name: Docker CI Action
on: 
  push: 
    branches: ['review-3']   
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
        - name: set lower case owner name
          run: /
            echo "REPO=${OWNER,,}" >>${GITHUB_ENV}
          env:
            OWNER: '${{ github.repository_owner }}'
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - run: / echo "repo ${REPO}"

        - name: Checkout repository
          uses: actions/checkout@v4
          
        - name: Login to the DockerHub
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push backend
          uses: docker/build-push-action@v6
          with:
            context: '{{defaultContext}}:backend'
            push: true
            tags: 'ghcr.io/${{ env.REPO }}/film_backend:latest'

        - name: Build and push frontend
          uses: docker/build-push-action@v6
          with:
            context: '{{defaultContext}}:frontend'
            push: true
            tags: 'ghcr.io/${{ env.REPO }}/film_frontend:latest'
       
        - name: Build and push server
          uses: docker/build-push-action@v6
          with:
            context: '{{defaultContext}}:nginx'
            push: true
            tags: 'ghcr.io/${{ env.REPO }}/film_server:latest'
